name: Out School Auto Apply

on:
  schedule:
    - cron: "20 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply
        if: always()
        env:
          APPLY_USERS: ${{ secrets.APPLY_USERS }}
          APPLY_SEND: ${{ secrets.APPLY_SEND }}
        run: |
          if python -u apply.py; then
            echo "success";
          else
            echo "fail";
          fi
